const SUPABASE_URL='https://mpphmngpemlcmlzepliq.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_xRieGhK_hEyeXhNCvmMIiQ_2O8q1StS';
// Preencha após criar o widget Cloudflare Turnstile.
const TURNSTILE_SITE_KEY='0x4AAAAAAFPpdUkvSYj_cvYr';
const wall=document.querySelector('#feedback-wall'),form=document.querySelector('#feedback-form'),statusMessage=document.querySelector('#feedback-status'),submitButton=document.querySelector('#feedback-submit'),message=document.querySelector('#feedback-message'),counter=document.querySelector('#feedback-counter');let turnstileToken='';
const headers={apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${SUPABASE_PUBLISHABLE_KEY}`};const setStatus=(text,type='')=>{statusMessage.textContent=text;statusMessage.className=`feedback-status ${type}`};const stars=value=>'★'.repeat(Number(value))+'☆'.repeat(5-Number(value));
function card(item){const article=document.createElement('article'),header=document.createElement('div'),identity=document.createElement('div'),name=document.createElement('h3'),date=document.createElement('time'),rating=document.createElement('span'),body=document.createElement('p');article.className='feedback-card';header.className='feedback-card-header';name.className='feedback-author';name.textContent=item.display_name;date.className='feedback-date';date.dateTime=item.created_at;date.textContent=new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(new Date(item.created_at));identity.append(name,date);rating.className='feedback-stars';rating.setAttribute('aria-label',`${item.rating} de 5 estrelas`);rating.textContent=stars(item.rating);header.append(identity,rating);body.className='feedback-message';body.textContent=item.message;article.append(header,body);return article}
async function loadFeedbacks(){try{const res=await fetch(`${SUPABASE_URL}/rest/v1/feedbacks?select=display_name,message,rating,created_at&order=created_at.desc&limit=30`,{headers});if(!res.ok)throw Error();const items=await res.json();wall.replaceChildren();if(!items.length){const empty=document.createElement('p');empty.className='feedback-empty';empty.textContent='Seja a primeira pessoa a compartilhar sua experiência.';wall.append(empty)}else items.forEach(item=>wall.append(card(item)))}catch{wall.replaceChildren();const error=document.createElement('p');error.className='feedback-error';error.textContent='Os feedbacks estarão disponíveis em breve.';wall.append(error)}finally{wall.setAttribute('aria-busy','false')}}
function initTurnstile(){if(!TURNSTILE_SITE_KEY){submitButton.disabled=true;setStatus('O envio protegido está sendo configurado. Volte em breve.');return}const render=()=>{if(!window.turnstile)return setTimeout(render,120);window.turnstile.render('#turnstile-widget',{sitekey:TURNSTILE_SITE_KEY,theme:'dark',callback:token=>{turnstileToken=token;submitButton.disabled=false},'expired-callback':()=>{turnstileToken='';submitButton.disabled=true},'error-callback':()=>{turnstileToken='';submitButton.disabled=true;setStatus('Não foi possível validar a proteção. Tente novamente.','error')}})};submitButton.disabled=true;render()}
message?.addEventListener('input',()=>counter.textContent=`${message.value.length} / 600`);form?.addEventListener('submit',async event=>{event.preventDefault();if(!form.checkValidity())return form.reportValidity();if(!turnstileToken)return setStatus('Confirme a validação de segurança antes de enviar.','error');const data=new FormData(form);submitButton.disabled=true;setStatus('Enviando seu feedback…');try{const res=await fetch(`${SUPABASE_URL}/functions/v1/submit-feedback`,{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({name:data.get('name'),message:data.get('message'),rating:Number(data.get('rating')),turnstileToken})});const payload=await res.json().catch(()=>({}));if(!res.ok)throw Error(payload.error||'Não foi possível enviar seu feedback.');form.reset();counter.textContent='0 / 600';turnstileToken='';window.turnstile?.reset();setStatus('Obrigada! Seu feedback já foi publicado.','success');await loadFeedbacks()}catch(error){setStatus(error.message||'Não foi possível enviar seu feedback. Tente novamente.','error')}finally{submitButton.disabled=!turnstileToken}});loadFeedbacks();initTurnstile();

