let allProducts=[];const grid=document.querySelector('#catalog-grid'),count=document.querySelector('#results-count'),panel=document.querySelector('#filter-panel'),c={category:document.querySelector('#category'),size:document.querySelector('#size'),color:document.querySelector('#color'),price:document.querySelector('#price'),sort:document.querySelector('#sort')};
function state(){const q=new URLSearchParams(location.search);return{category:q.get('categoria')||'todos',size:q.get('tamanho')||'',color:q.get('cor')||'',price:q.get('preco')||'',sort:q.get('ordem')||'new'}}
function load(s){Object.keys(c).forEach(k=>c[k].value=s[k]||'');syncCustomSelects()}
function save(){const q=new URLSearchParams();if(c.category.value!=='todos')q.set('categoria',c.category.value);if(c.size.value)q.set('tamanho',c.size.value);if(c.color.value)q.set('cor',c.color.value);if(c.price.value)q.set('preco',c.price.value);if(c.sort.value!=='new')q.set('ordem',c.sort.value);const x=q.toString()?'?'+q:'';history.replaceState(null,'','produtos.html'+x);sessionStorage.setItem('uzzelettiCatalog',x)}
function render(){let a=[...allProducts],s={category:c.category.value,size:c.size.value,color:c.color.value,price:c.price.value,sort:c.sort.value};if(s.category!=='todos')a=a.filter(p=>p.category===s.category);if(s.size)a=a.filter(p=>p.sizes.includes(s.size));if(s.color)a=a.filter(p=>p.colors.includes(s.color));if(s.price){let[m,x]=s.price.split('-').map(Number);a=a.filter(p=>p.price>=m&&(!x||p.price<=x))}if(s.sort==='low')a.sort((a,b)=>a.price-b.price);if(s.sort==='high')a.sort((a,b)=>b.price-a.price);if(s.sort==='new')a.sort((a,b)=>Number(b.new)-Number(a.new));grid.innerHTML=a.length?a.map(productCard).join(''):'<div class="empty-state"><h3>Nenhum produto encontrado</h3><p>Experimente remover um filtro.</p><button class="btn btn-outline" id="empty-clear">Limpar filtros</button></div>';count.textContent=`${a.length} ${a.length===1?'produto encontrado':'produtos encontrados'}`;save();document.querySelector('#empty-clear')?.addEventListener('click',clear)}
function close(){panel.classList.remove('open');document.body.classList.remove('menu-open')}function clear(){load({category:'todos',size:'',color:'',price:'',sort:'new'});render();close()}
async function init(){if(!grid)return;enhanceSelects();allProducts=await getProducts();load(state());render();document.querySelector('#apply-filters').onclick=()=>{render();close()};document.querySelector('#clear-filters').onclick=clear;document.querySelector('#open-filters').onclick=()=>{panel.classList.add('open');document.body.classList.add('menu-open');document.querySelector('#close-filters').focus()};document.querySelector('#close-filters').onclick=close;document.querySelector('.filter-backdrop').onclick=close;c.sort.onchange=render;addEventListener('keydown',e=>{if(e.key==='Escape')close()})}
const customSelects=[];
function closeCustomSelects(except){customSelects.forEach(item=>{if(item!==except){item.root.classList.remove('open');item.button.setAttribute('aria-expanded','false');item.list.hidden=true}})}
function syncCustomSelects(){customSelects.forEach(item=>{const selected=item.select.options[item.select.selectedIndex];item.button.querySelector('span').textContent=selected?.textContent||'';item.options.forEach(option=>{const active=option.dataset.value===item.select.value;option.classList.toggle('selected',active);option.setAttribute('aria-selected',String(active))})})}
function enhanceSelects(){if(!matchMedia('(max-width: 900px)').matches)return;Object.values(c).forEach(select=>{const root=document.createElement('div');root.className='custom-select';select.parentNode.insertBefore(root,select);root.appendChild(select);select.classList.add('select-native');const button=document.createElement('button');button.type='button';button.className='custom-select-button';button.setAttribute('aria-haspopup','listbox');button.setAttribute('aria-expanded','false');button.innerHTML='<span></span><b aria-hidden="true">⌄</b>';const list=document.createElement('div');list.className='custom-select-options';list.setAttribute('role','listbox');list.hidden=true;const item={root,select,button,list,options:[]};[...select.options].forEach(nativeOption=>{const option=document.createElement('button');option.type='button';option.className='custom-select-option';option.setAttribute('role','option');option.dataset.value=nativeOption.value;option.textContent=nativeOption.textContent;option.addEventListener('click',()=>{select.value=option.dataset.value;select.dispatchEvent(new Event('change',{bubbles:true}));syncCustomSelects();closeCustomSelects();button.focus()});option.addEventListener('keydown',event=>{const index=item.options.indexOf(option);if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();item.options[(index+(event.key==='ArrowDown'?1:-1)+item.options.length)%item.options.length].focus()}if(event.key==='Home'||event.key==='End'){event.preventDefault();item.options[event.key==='Home'?0:item.options.length-1].focus()}if(event.key==='Escape'){event.preventDefault();closeCustomSelects();button.focus()}});item.options.push(option);list.appendChild(option)});button.addEventListener('click',()=>{const opening=list.hidden;closeCustomSelects(opening?item:null);root.classList.toggle('open',opening);button.setAttribute('aria-expanded',String(opening));list.hidden=!opening});button.addEventListener('keydown',event=>{if(['ArrowDown','ArrowUp','Enter',' '].includes(event.key)){event.preventDefault();if(list.hidden)button.click();const selected=Math.max(0,item.options.findIndex(option=>option.dataset.value===select.value));item.options[event.key==='ArrowUp'?Math.max(0,selected-1):selected].focus()}if(event.key==='Escape')closeCustomSelects()});root.append(button,list);customSelects.push(item)});syncCustomSelects();document.addEventListener('click',event=>{if(!event.target.closest('.custom-select'))closeCustomSelects()})}
init();
